export const testData = [
	{
		title: 'Up & Coming Astronaut',
		name: 'Alyssa Carson',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 1,
		dateISO: new Date('November 1, 2022').toISOString(),
		id: 1,
	},
	{
		title: 'CEO Coinbase',
		name: 'Brian Armstrong',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 2,
		dateISO: new Date('November 2, 2022').toISOString(),
		id: 2,
	},
	{
		title: 'CEO MicroStrategy',
		name: 'Michael Saylor',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 3,
		dateISO: new Date('November 3, 2022').toISOString(),
		id: 3,
	},
	{
		title: 'Singer / Entrepeneur',
		name: 'Rihanna',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 4,
		dateISO: new Date('November 4, 2022').toISOString(),
		id: 4,
	},
	{
		title: 'CEO Tesla',
		name: 'Elon Musk',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 5,
		dateISO: new Date('November 5, 2022').toISOString(),
		id: 5,
	},
	{
		title: 'Pop icon / Music Producer',
		name: 'Robyn',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 6,
		dateISO: new Date('November 6, 2022').toISOString(),
		id: 6,
	},
	{
		title: 'Frontend Developer / FOTD Founder',
		name: 'Henric Hiljanen',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 7,
		dateISO: new Date('November 7, 2022').toISOString(),
		id: 7,
	},
	{
		title: 'Award Winning Art Director',
		name: 'Maja Gerhardsson',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 8,
		dateISO: new Date('November 8, 2022').toISOString(),
		id: 8,
	},
	{
		title: 'NFT Enthusiast / Entrepeneur',
		name: 'Gary Vee',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 9,
		dateISO: new Date('November 9, 2022').toISOString(),
		id: 9,
	},
	{
		title: 'Pop icon / Singer',
		name: 'Lady Gaga',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 10,
		dateISO: new Date('November 10, 2022').toISOString(),
		id: 10,
	},
	{
		title: 'Creator of Ethereum',
		name: 'Vitalik Buterin',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 11,
		dateISO: new Date('November 11, 2022').toISOString(),
		id: 11,
	},
	{
		title: 'Master of melodies / Music Producer',
		name: 'Avicii',
		imageUrl: '',
		year: 2022,
		month: 10,
		monthDay: 30,
		dateISO: new Date('November 30, 2022').toISOString(),
		id: 12,
	},
	{
		title: 'Title text',
		name: 'Alyssa Carson',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 1,
		dateISO: new Date('December 1, 2022').toISOString(),
		id: 13,
	},
	{
		title: 'Title text',
		name: 'Brian Armstrong',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 4,
		dateISO: new Date('December 4, 2022').toISOString(),
		id: 14,
	},
	{
		title: 'Title text',
		name: 'Michael Saylor',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 6,
		dateISO: new Date('December 6, 2022').toISOString(),
		id: 15,
	},
	{
		title: 'Title text',
		name: 'Rihanna',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 9,
		dateISO: new Date('December 9, 2022').toISOString(),
		id: 16,
	},
	{
		title: 'Title text',
		name: 'Elon Musk',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 11,
		dateISO: new Date('December 11, 2022').toISOString(),
		id: 17,
	},
	{
		title: 'Title text',
		name: 'Robyn',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 19,
		dateISO: new Date('December 19, 2022').toISOString(),
		id: 18,
	},
	{
		title: 'Title text',
		name: 'Henric Hiljanen',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 24,
		dateISO: new Date('December 24, 2022').toISOString(),
		id: 19,
	},
	{
		title: 'Title text',
		name: 'Maja Gerhardsson',
		imageUrl: '',
		year: 2022,
		month: 11,
		monthDay: 31,
		dateISO: new Date('December 31, 2022').toISOString(),
		id: 20,
	},
	{
		title: 'Title text',
		name: 'Gary Vee',
		imageUrl: '',
		year: 2023,
		month: 0,
		monthDay: 2,
		dateISO: new Date('January 2, 2023').toISOString(),
		id: 21,
	},
	{
		title: 'Title text',
		name: 'Lady Gaga',
		imageUrl: '',
		year: 2023,
		month: 0,
		monthDay: 5,
		dateISO: new Date('January 5, 2023').toISOString(),
		id: 22,
	},
	{
		title: 'Title text',
		name: 'Vitalik Buterin',
		imageUrl: '',
		year: 2023,
		month: 0,
		monthDay: 9,
		dateISO: new Date('January 9, 2023').toISOString(),
		id: 23,
	},
	{
		title: 'Title text',
		name: 'Avicii',
		imageUrl: '',
		year: 2023,
		month: 0,
		monthDay: 31,
		dateISO: new Date('January 31, 2023').toISOString(),
		id: 24,
	},
];
